language: node_js
node_js:
  - "20.9"

os: linux
dist: jammy

install:
  - echo "Installing npm packages..."
  - npm install --verbose &

  # Keep-alive output loop so Travis doesn't timeout
  - while sleep 30; do echo "Still installing..."; done &
  - wait
